---
- hosts: all
  become: yes
  tasks:
  - name: Disable root login over SSH
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
    notify:
      - restart sshd
  - name: Disable password login
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify:
      - restart sshd

  - name: Install Oh-My-ZSH
    ansible.builtin.git:
      repo: 'https://github.com/lunchbox93/.oh-my-zsh.git'
      dest: /home/lunchbox/.oh-my-zsh/
    become: yes
    become_user: lunchbox
  - name: copy zsh config
    copy:
      src: configs/zshconfig2
      dest: /home/lunchbox/.zshrc

  handlers:
  - name: restart sshd
    service:
      name: sshd
      state: restarted