---
- hosts: all
  become: yes
  tasks:
  - name: Install basic packages
    apt:
      name: curl,ntp,nano,net-tools,wget,iftop,python3-pip
  - name: Install the packages for postfix and mysql
    apt:
      name: postfix,postfix-mysql,postfix-doc,mariadb-client,mariadb-server,openssl,getmail4,rkhunter,python-mysqldb,binutils,dovecot-imapd,dovecot-pop3d,dovecot-mysql,dovecot-sieve,sudo,patch

  - name: Make sure pymysql is present
    pip:
      name: pymysql
      state: present

  - name: Install the packages for spamassassin and clamav
    apt:
      name: amavisd-new,spamassassin,clamav,clamav-daemon,unzip,bzip2,arj,nomarch,lzop,cabextract,apt-listchanges,libnet-ldap-perl,libauthen-sasl-perl,clamav-docs,daemon,libio-string-perl,libio-socket-ssl-perl,libnet-ident-perl,zip,libnet-dns-perl,postgrey
  - name: Install apache2 and php
    apt:
      name: apache2,apache2-doc,apache2-utils,libapache2-mod-php,php7.2,php7.2-common,php7.2-gd,php7.2-mysql,php7.2-imap,php7.2-cli,php7.2-cgi,libapache2-mod-fcgid,apache2-suexec-pristine,php-pear,mcrypt,imagemagick,libruby,libapache2-mod-python,php7.2-curl,php7.2-intl,php7.2-pspell,php7.2-recode,php7.2-sqlite3,php7.2-tidy,php7.2-xmlrpc,php7.2-xsl,memcached,php-memcache,php-imagick,php-gettext,php7.2-zip,php7.2-mbstring,php-soap,php7.2-soap,libapache2-reload-perl,php7.2-opcache,php-apcu,php7.2-fpm
  - name: Install firewall and logging
    apt:
      name: vlogger,webalizer,awstats,geoip-database,libclass-dbi-mysql-perl,certbot,fail2ban,ufw

  - name: Disable service apparmor
    ansible.builtin.service:
      name: apparmor
      enabled: no
  - name: Stop service apparmor
    ansible.builtin.service:
      name: apparmor
      state: stopped
  - name: Template postfix
    ansible.builtin.template:
      src: configs/postfix-master
      dest: /etc/postfix/master.cf
  - name: Disable service spamassassin
    ansible.builtin.service:
      name: spamassassin
      enabled: no
  - name: Stop service spamassassin
    ansible.builtin.service:
      name: spamassassin
      state: stopped
  - name: Start service clam-av
    ansible.builtin.service:
      name: clamav-daemon
      state: started
  - name: Change the authentication plugin of MySQL root user to mysql_native_password
    shell: mysql -u root -e 'UPDATE mysql.user SET plugin="mysql_native_password" WHERE user="root" AND host="localhost"'

  - name: Enable remote login to mysql
    lineinfile:
      path: /etc/mysql/mariadb.conf.d/50-server.cnf
      regexp: '^bind-address'
      line: 'bind-address = 0.0.0.0'
      backup: yes

  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: suexec
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: rewrite
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: ssl
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: actions
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: include
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: cgi
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: dav_fs
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: dav
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: auth_digest
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: headers
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: actions
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: proxy_fcgi
  - name: Enable the Apache2 module
    community.general.apache2_module:
      state: present
      name: alias
  - name: Template apache module
    ansible.builtin.template:
      src: configs/httpoxy
      dest: /etc/apache2/conf-available/httpoxy.conf
  - name: Enable httpoxy conf
    ansible.builtin.shell: a2enconf httpoxy

  - name: Template awstats cron
    ansible.builtin.template:
      src: configs/stats
      dest: /etc/cron.d/awstats
  - name: Template fail2ban config
    ansible.builtin.template:
      src: configs/fail2ban
      dest: /etc/fail2ban/jail.local
  - name: Template fail2ban filters
    ansible.builtin.copy:
      src: configs/f2b/
      dest: /etc/fail2ban/filter.d/

  - name: Restart service httpd
    ansible.builtin.service:
      name: apache2
      state: restarted